global:
  scrape_interval: 5s
  external_labels:
    monitor: 'taxi-monitor'

scrape_configs:
  - job_name: 'client-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['client-service:8081']

  - job_name: 'driver-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['driver-service:8082']

  - job_name: 'car-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['car-service:8083']

  - job_name: 'ride-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ride-service:8084']

  - job_name: 'rate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rate-service:8085']

  - job_name: 'promo-code-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['promo-code-service:8090']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8091']