apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka/
            - name: SPRING_APPLICATION_NAME
              value: apigateway
            - name: SPRING_MVC_TIMEZONE
              value: Europe/Minsk
          image: parent-project-apigateway:latest
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:8080/
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
