apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eurekaserver
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: eurekaserver
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_NAME
              value: eurekaserver
          image: parent-project-eurekaserver:latest
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:8761/
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: eurekaserver
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
